trigger:
  branches:
    include:
    - '*'  

jobs:
- job: linux_32bit
  pool:
    vmImage: 'ubuntu-18.04'
  
  strategy:
    matrix:
      go12:
        go_version: "1.12"
      go13:
        go_version: "1.13"
      go14:
        go_version: "1.14"
    maxParallel: 3
  
  variables:
    go_project: "godbg"
  
  steps:
  - script: |
      docker pull i386/ubuntu:bionic
      docker run -v $(pwd):/$(go_project) i386/ubuntu:bionic /bin/bash -c "cd $(go_project) && \
      apt-get -y update && \
      apt-get -y install software-properties-common && \
      apt-get -y install git && \
      add-apt-repository ppa:longsleep/golang-backports && \
      apt-get -y install golang-$(go_version)-go && \
      export PATH=$PATH:/usr/lib/go-$(go_version)/bin && \
      env && \
      go version && \
      uname -a && \
      echo '???\n' && \
      ls  && \
      echo '???\n' && \
      cat Makefile && \
      make test"
    displayName: 'linux 32bit'
