trigger:
  branches:
    include:
    - '*'  

pool:
  vmImage: 'ubuntu-18.04'

strategy:
  matrix:
    go12:
      go_version: "1.12"
    go13:
      go_version: "1.13"
    go14:
      go_version: "1.14"
  maxParallel: 3

variables:
  GOBIN:  '$(GOPATH)/bin' 
  GOVERSION: go_version
  GOPATH: '$(system.defaultWorkingDirectory)/gopath'
  modulePath: '$(GOPATH)/src/github.com/$(build.repository.name)'

steps:
- script: |
    sudo add-apt-repository ppa:gophers/archive
    sudo apt update
    sudo apt install golang-$(GOVERSION)-go
    go version
    make test
  workingDirectory: '$(modulePath)'
  displayName: 'linux amd64'
