trigger:
  branches:
    include:
    - '*'  

jobs:
- job: linux_32bit
  pool:
    vmImage: 'ubuntu-18.04'
  
  strategy:
    matrix:
      go12:
        go_version: "1.12"
      go13:
        go_version: "1.13"
      go14:
        go_version: "1.14"
    maxParallel: 3
  
  variables:
    GOPROJECT: "godbg"
  
  steps:
  - script: |
      docker pull i386/ubuntu:bionic
      docker run -v $(pwd):/$(GOPROJECT) i386/ubuntu:bionic /bin/bash -c "cd $(GOPROJECT) && \
      apt -y update && \
      apt -y install software-properties-common && \
      add-apt-repository ppa:gophers/archive && \
      apt -y install golang-$(go_version) && \
      go version && \
      uname -a && \
      make test"
    displayName: 'linux 32bit'
